### ISSUE TITLE
How do i uninstall this package?

### ISSUE THREAD

**Issue by mejliu** [FichteFoll/InsertDate#23]
It seems that this package cannot be removed. Everytime when I remove it, it always remind me some error.
So, could you kindly tell me how to remove it, thank you very very much.

**Comment by FichteFoll** [comment]
Did this solve by itself?

**Comment by mejliu** [comment]
Thank you for your reply.
In face, it cannot be removed by "remove packages", because it also remind me some error. Then, I tried to delete packages manually, but it will re-install again. In the end, only when i delete it from "package control.sublime-settings" can it be removed.

**Comment by FichteFoll** [comment]
Please paste the error here so I can (potentially) reproduce and fix the problem.

**Comment by mejliu** [comment]
![p](https://cloud.githubusercontent.com/assets/4575879/9387519/83fea3b8-4793-11e5-988f-afb0b9574130.PNG)

Sorry for language inconvenience. It says:
[Winerror 32] Another process is using this file, and the process can not access...

I will be appreciated if you can fix this problem. Thank you.

**Comment by FichteFoll** [comment]
Is there anything else in the console perhaps? `View > Console`

**Comment by mejliu** [comment]
Here is the error msg:

```c
unloading plugin InsertDate.insert_date
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 63, in unload_plugin
    unload_module(m)
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 38, in unload_module
    module.plugin_unloaded()
  File "insert_date in C:\Users\Jun Liu\AppData\Roaming\Sublime Text 3\Installed Packages\InsertDate.sublime-package", line 285, in plugin_unloaded
ImportError: No module named 'format_date'
reloading Packages/InsertDate/insert_date.sublime-settings
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
error: Package Control

An error occurred while trying to remove the installed package file for InsertDate.

[WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\Jun Liu\\AppData\\Roaming\\Sublime Text 3\\Installed Packages\\InsertDate.sublime-package'
ignored packages updated to: ["Markdown", "Vintage"]
reloading plugin InsertDate.insert_date
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 71, in reload_plugin
    unload_module(m)
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 38, in unload_module
    module.plugin_unloaded()
  File "insert_date in C:\Users\Jun Liu\AppData\Roaming\Sublime Text 3\Installed Packages\InsertDate.sublime-package", line 285, in plugin_unloaded
ImportError: No module named 'format_date'
reloading Packages/InsertDate/insert_date.sublime-settings
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
```

**Comment by FichteFoll** [comment]
Okay, I know where this is coming from. Thanks for the report. Will have a fix up shortly.
