### ISSUE TITLE
Not working in Sublime Text 3 build 3143

### ISSUE THREAD

**Issue by silanfa** [FichteFoll/InsertDate#37]
InsertDate is no longer working after I upgraded to the released version of ST 3 (build 3143). The InsertDate options in command palette has disappeared.

Command palette in ST 3 build 3143
![image](https://user-images.githubusercontent.com/3341537/30395438-23df0c80-9894-11e7-8320-dec7c3081c58.png)

Compare to ST 2
![image](https://user-images.githubusercontent.com/3341537/30395316-b8e3f986-9893-11e7-9d42-31913faf2e74.png)

**Comment by FichteFoll** [comment]
Works perfectly fine in 3142 at least.

Can you post your ST console's content?

**Comment by silanfa** [comment]
Console log from after using Package Control to remove and reinstall InsertDate.

```
ignored packages updated to: ["InsertDate", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
Package Control: The dependency 'pytz' is not currently installed; installing...
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'pytz' has successfully been installed or updated
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin InsertDate.insert_date
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "insert_date in /Users/kluk/Library/Application Support/Sublime Text 3/Installed Packages/InsertDate.sublime-package", line 8, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "format_date in /Users/kluk/Library/Application Support/Sublime Text 3/Installed Packages/InsertDate.sublime-package", line 7, in <module>
ImportError: No module named 'pytz.exceptions'
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

**Comment by FichteFoll** [comment]
Have you tried restarting ST after the installation? It appears like installation of the dependency didn't go smoothly.

**Comment by silanfa** [comment]
I restarted ST after the installation yesterday and it still didn't work.

Somehow it's working now after restart ST again this morning. ¯\\\_(ツ)_/¯

Thanks for helping!
